import feladatok
feladatok.feladat1()
feladatok.feladat2(14550)
feladatok.feladat3(4455)
feladatok.feladat4()
feladatok.feladat5()
feladatok.feladat6()
feladatok.feladat7()
feladatok.feladat8()
feladatok.feladat9()
feladatok.feladat10()
feladatok.feladat11(6,12)
feladatok.feladat12(4,10)
feladatok.feladat13(4)
feladatok.feladat14("szerda","programozás")